# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='perfil',
        ),
    ]
