# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170726_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
