# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_auto_20170719_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='contatos_bloqueados',
            field=models.ManyToManyField(related_name='_perfil_contatos_bloqueados_+', to='perfis.Perfil'),
        ),
    ]
